apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
  - name: mutating-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        mutating-webhook-enabled: "true"
    clientConfig:
      service:
        name: mutating-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjRENDQWxpZ0F3SUJBZ0lVSEx1K1BkUHZpTnFBMXpvM3paYmVaNUhPUk1nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VERUxNQWtHQTFVRUJoTUNSRVV4RURBT0JnTlZCQWdUQjBKaGRtRnlhV0V4RHpBTkJnTlZCQWNUQmsxMQpibWxqYURFUU1BNEdBMVVFQ2hNSFUybGxiV1Z1Y3pFTU1Bb0dBMVVFQ3d3RFVpWkVNQjRYRFRJME1EY3lNakU0Ck5ERXdNRm9YRFRJNU1EY3lNVEU0TkRFd01Gb3dVREVMTUFrR0ExVUVCaE1DUkVVeEVEQU9CZ05WQkFnVEIwSmgKZG1GeWFXRXhEekFOQmdOVkJBY1RCazExYm1samFERVFNQTRHQTFVRUNoTUhVMmxsYldWdWN6RU1NQW9HQTFVRQpDd3dEVWlaRU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMnVzSHFvSi91S1hECjVuaEkwbktmcGJ3M2VpbklXSUhOUVpsL0Eza3NXVDBYWUxnQzdOT1MxeTNkRk8yRTZMUHVtUGZFSStsaS9JR3oKbndIYytBUUFWMVNST0FVVFNUcnlaTFRXU05sU0Y5anU2VVhKTSs1T21pRmptRXNNOW03K1JBREdPb3ZlZ0t3Nwo0cDRwYW9WQ0JYNXM1SnpENk9ZODh1dGtHTDA5cVEvSm94Tnp0K2NXQk1vM2JjUGxsek9DdDdHY0s0RHJ6MzJ2CkJkRi9kN1MxcVVleWJkVXlqOG9VZE8xL1FGZnRYdzcrL3ZTaXpyU2hWZWZCbi9SbkRnWlMzUnI3L3BiNng5SFIKZktsSldHTFU2VVYwTS9UNmgvN1dzd0FjcDE2WG5zRTJucDNIWjZuNGN0UVJRMGhHbW9sWUJkL29vYmptajJadQowVmNUNG5tTW53SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QWRCZ05WSFE0RUZnUVV5ekIxMldpbElUdXBHZjZoeG94U1NaR2V0YlV3RFFZSktvWklodmNOQVFFTEJRQUQKZ2dFQkFBQ0FIZzdyVUtJd3c5RkhvZXlKVWplU1hJRmlVT3hLT0MxajhpQlVKdG9ZNERRRGV3UnRqMEZxY3p5NApQbnJ3T093YnVoazhYeWgvTGFUYk5mL3hCZFJ2S0Rhcm11Uy9XZ0VpUkYvWE9rNDA4TDRuYW9rVThWd0xrVkdHCm5CblM3bHhJZ2tSaUZLMFppckhUN0wzN0lDSXJ6cTRYV3R2M1BIcFNOeDJJSTZkbmVaR2NlMXIrQThDZjhtVEcKQ3o3d1RncGowaHRVZWVJQkFCTVdHbVhkTzdrQlNsQUFNZVJFR2RBT0tOMnhaWGtvR3RkdE1FVTFVN3dOMlJrZwozU2x6WUJma2o4WEgycEF5Y2FDNXNZV0ZkVFRVR2JXbDh3czU4ZGd5TFNkalhXd2p6TXNSZUtyenF0Nndya0d2ClJ4VndGbWZJbDJwN3RKVnJIcjVPQlVtMW5rbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]