FROM golang:1.22-alpine AS dev-env

WORKDIR /app

FROM dev-env AS build-env
COPY go.mod /go.sum /app/
RUN go mod download

COPY . /app/

RUN CGO_ENABLED=0 go build -o /webhook

FROM alpine:3.10 AS runtime

ENV KUBERNETES_SERVICE_HOST=https://127.0.0.1
ENV KUBERNETES_SERVICE_PORT=6443

COPY --from=build-env /webhook /usr/local/bin/webhook
RUN chmod +x /usr/local/bin/webhook

ENTRYPOINT ["webhook"]

